### ISSUE TITLE
naming issue

### ISSUE THREAD

**Issue by randomwangran** [casdu/huikan#11]
I think it is too ~dangerous~ to put the people's real name on the open web.

It's potentially dangerous to people who has malicious purpose.

Better to just put their user's name or the name they perfer. It's trivial for CASDUer to know who s/he is, but not that easy for malicious people.

It's not saying that we want to hide our identity. It just raise the effort to those malicious people. The world is too complex, somtimes our good intension is translated into a bad one.

I think most of the people in this world do good thing, but that's not to say we do not protect ourself.

**Comment by yangxcasdu** [comment]
在论坛上，一种保护隐私的方式是给帖子加权限，比如历年远征路线或者总结，只有在论坛中正式会员可以查看。另外一种方式是指开放特定板块给用户组，例如车协政务院。不知github上有没有这种办法。

给姓名加密问题，是否需要询问作者他们愿意取的名字（名字缩写？省略姓？名字拼音 ）

**Comment by randomwangran** [comment]
> 我们还会叫着彼此的外号，我想这就是车协最有魅力的地方之一

                   -- 卢导叨叨叨 Luyao 2015级管理学院 2016年远征队队员

**Comment by randomwangran** [comment]
Not really an issue, but it's just a perference for someone.
