### ISSUE TITLE
首页添加 logo 大家怎么看?

### ISSUE THREAD

**Issue by randomwangran** [casdu/huikan#12]

**Comment by randomwangran** [comment]
not very secure to put jpg file in this rep.

Just *.md file?

**Comment by yangxcasdu** [comment]
@randomwangran   看不到图片显示 (╥﹏╥)

**Comment by randomwangran** [comment]
可以把这个仓库下载，找到` casdu.jpg` 这个文件。

**Comment by yangxcasdu** [comment]
刚刚打开页面居然看到最开始的logo了~

**Comment by randomwangran** [comment]
@yangxcasdu 

那就留下了？

**Comment by yangxcasdu** [comment]
我觉得可以留下 ^^

**Comment by randomwangran** [comment]
okay. I will close this issue.
