### ISSUE TITLE
关于电子版会刊阅读体验问卷（19.md）

### ISSUE THREAD

**Issue by yangxcasdu** [casdu/huikan#14]
## 设置问卷原因：

1、了解大家的对于电子会刊需求以及意愿
2、了解大家对于19会刊采取名字全拼加密方式的看法
3、进一步普及电子会刊以及 GitHub 平台

## 问题设置：

一、阅读意愿：
是否经常阅读会刊？           经常   有时   偶尔   没有
是否有经常接触纸质版往年会刊机会？   是，我手头保存  无所谓    否，没有
是否愿意阅读纯文字电子版会刊？      很愿意   愿意   无所谓  不愿意
是否愿意将电子版会刊推荐给他人？   很愿意   愿意   无所谓  不愿意

二、阅读感受问题：
1、阅读难度
点击链接阅读是否困难？   非常  一般   不困难  无所谓
2、阅读流畅度 
阅读是否流畅？                  流畅   一般   不流畅 （原因是：——）

三、隐私问题
1、对于姓名加密是否有必要？  非常   一般   无所谓   不必要 
2、对于名字加密方式为全拼接受程度?    接受   一般   无所谓   不接受
3、其他可行加密方式（如有请列举）

四、后续跟进意愿(车协资料库有14、15、16、17年pdf电子版)
1、是否对跟进并且补充会刊有兴趣？  
[关于扩展会刊](https://github.com/casdu/huikan/issues/5)
2、是否有时间在课余跟进会刊？（任务细化为 联系主编  联系作者  转载 ）
有时间  暂无时间但是愿意抽空学习   愿意在寒暑假期学习
2、你认为的跟进会刊的难度大小？   非常难  一般   比较简单
 [如何用markdown格式编辑](https://github.com/casdu/huikan/issues/9) 
也许我应该写一篇我是如何操作这些的一个文章（待更）

## 问卷面向对象：

1、各季会刊编辑人员
2、在校主席团
3、在校会员
3、离校老会员

## 问卷载体：
1、问卷星or论坛投票功能？

**Comment by randomwangran** [comment]
> 问卷星or论坛投票功能？

If most of the CASDUers feel Wechat is the easiest way to do it, can we do it in Wechat?

**Comment by yangxcasdu** [comment]
嗯嗯，如果扩大问卷受众的话，可以用微信传播，大部分离校会员使用微信，而在校会员使用qq。
问卷星链接可通过微信/朋友圈/QQ/邮件/短信分发，功能还是比较强大的，便于收集数据进行整理。
论坛上可以贴出问题内容和问卷星链接。

**Comment by randomwangran** [comment]
看到自己的坑，还没填。


什么时间打算发出这个问卷调查？

我可以把 #5 和 #9 ,稍微扩展一些。

**Comment by randomwangran** [comment]
> 也许我应该写一篇我是如何操作这些的一个文章（待更）

我们可以一起起草。写成一份文档。

**Comment by randomwangran** [comment]
或者采用：http://bbs.casdu.cn/forum.php?mod=viewthread&tid=11792

调查问卷的模式，这样的好处是，能得到更多的反馈。

不好的地方是，让人打字很麻烦的。

**Comment by randomwangran** [comment]
受到启发：https://github.com/randomwangran/draw

慢慢收集，历届会刊的封面，然后做成这样像表格一个的图片，链接指向纯文本地址。

**Comment by yangxcasdu** [comment]
时间线可以放缓一些，等我们都做好手头的再发布。
我这边想的是  **以面对的问题、问题如何解决的思路**来写，
1、注册问题
2、页面介绍
3、加入编辑
4、基础操作（讨论区）
5、会刊更新

大概需要一周？

问卷体验的时效性不大，不需要马上发出，等做好了随时可以发。

但是很重要的第一步，需要引导大家进行一些阅读，这样之后再进行阅读体验的调查。

> 调查问卷的模式，这样的好处是，能得到更多的反馈。

赞同，但是费很多时间，如果是小范围的询问（找比较热心的会员），会比较好。
如果做访谈式调查，
可以将之放在正式问卷发布的之前作为问卷普及之前的初次调查，
之后再根据初次访谈内容补充和修改更多的选项，
最后将正式的选择式问卷面对所有会员发布。

**Comment by yangxcasdu** [comment]
[正在更新的问题](https://github.com/yangxcasdu/2019.md/blob/master/在Github遇到问题以及解决办法.md)

**Comment by yangxcasdu** [comment]
来自一位作者的阅读反馈：

> 转载的效果挺好，一定程度上能增加传播度。我之前还以为是传可翻页的图片，就是翻页什么的也更舒服，像是看书。
> 没想到是文字版，排版弄得挺好，也有超链接，只是github好像没有目录的快捷显示，每次要拉回首页，不过这是网站的限制了小问题。

**Comment by randomwangran** [comment]
> 只是github好像没有目录的快捷显示，每次要拉回首页

2018.md 的目录超帅的。

**Comment by randomwangran** [comment]
@yangxcasdu 

~~How about this: https://github.com/casdu/huikan/blob/2019-TOC/2019.md   ?~~

**Comment by randomwangran** [comment]
手机端可能不好弄, 电脑上可以的用键盘上 `HOME` 键

**Comment by yangxcasdu** [comment]
找到了，笔记本上是 Fn + Home ！

**Comment by randomwangran** [comment]
If any problem, please re-open.
