### ISSUE TITLE
收集封面

### ISSUE THREAD

**Issue by randomwangran** [casdu/huikan#15]

**Comment by yangxcasdu** [comment]
12、13、14、15季已经找到。

**Comment by randomwangran** [comment]
![image](https://user-images.githubusercontent.com/8197831/76674215-1ecb9100-6583-11ea-8254-6d03c2525d6a.png)

**Comment by randomwangran** [comment]
![image](https://user-images.githubusercontent.com/8197831/76674239-779b2980-6583-11ea-90f5-fe4a364c2ba9.png)

**Comment by randomwangran** [comment]
感觉会牵扯很多麻烦的事情。以后可以考虑。
