### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by randomwangran** [casdu/huikan#6]
最好是鼠标悬浮在 链接上， 自动 popup 出图片。

**Comment by yangxcasdu** [comment]
我目前的操作中，没有能够查看任何一张图片，点进去之后网页崩溃了，不知道是不是浏览器问题。

如果以后会刊以这种可编辑的文字化方式存在，图片不能显示就少了很多乐趣和意思。

**Comment by randomwangran** [comment]
> 我目前的操作中，没有能够查看任何一张图片

这是对的，我们还没有做到把图片集成进来的程度。

这是 Markdown 本身的劣势。

这种轻量化的标记语言，设计理念主要是处理纯文字的文档。

但是现在技术上也有很多发展，我目前想到的办法是 用 latex 来渲染 markdown 的文本(当然这其中包含很多转换的东西)。

可以参考 https://github.com/casdu/huikan/issues/4 

不过，这其中的工作量很大，我不认为我们能立即用上。只是一种可能性。

另外，

> 点进去之后网页崩溃了，不知道是不是浏览器问题。

最好把你遇到的问题，[新开一个 Issue](https://github.com/casdu/huikan/issues/new), 在里面详细描述你的问题。我们看怎么来解决。

有什么疑问一定留下，我们尽量回答。

**Comment by randomwangran** [comment]
> 图片不能显示就少了很多乐趣和意思。

关于电子会刊趣味性的东西：我想分享一些我的东西。

我为什么维护这个仓库呢？而且隔了这么长时间？

[因为我觉得很有意思。](https://github.com/casdu/huikan/issues/5)
