### ISSUE TITLE
如何在网页端编辑会刊

### ISSUE THREAD

**Issue by yangxcasdu** [casdu/huikan#7]
需否要下载GitHub Desktop [scientific-online-searching才能下载这个软件吗？](https://www.cnblogs.com/roadone/p/7997644.html)

如果在网页端编辑，文字的格式问题如何处理，我指的是 字体大小颜色超链接跳转。
在评论这里可以找到### 大小、**加粗**、

> 引用

1. 列表。
但是在md文件中没有找到上面这一列，是否需要用代码实现？

**Comment by yangxcasdu** [comment]
#4

**Comment by yangxcasdu** [comment]
1.[基本大标题小标题缩进引用超链接](https://blog.csdn.net/weixin_39923425/article/details/79584378)
2.[生成目录](https://blog.csdn.net/dss_dssssd/article/details/82959037)

**Comment by randomwangran** [comment]
> 如何在网页端编辑会刊

If you want to edit huikan, you must be our team member. You already become our team member. So, you can edit the Huikan by just clicking this button:

![image](https://user-images.githubusercontent.com/8197831/74607745-4aa14700-50a9-11ea-8447-4b190bfaac7d.png)

You don't have to download GitHub Desktop.

I once play with it but I feel it is too heavy. If you don't have a powerful computer, it makes you feel bad. But here, if casduer only wants to edit something, it is not necessary.

However, if you want the full function of Git, [use command line version](https://git-scm.com/download/win), it is fast and easy to do some simple commands. Don't get me wrong, it's not about teaching programming, it is just so easy to do some basic git commands using command line version.

[I think we better to open a new issue to discuss how to edit the Huikan using Markdown.](https://github.com/casdu/huikan/issues/9)


Feel free to ask any question.

**Comment by randomwangran** [comment]
An example I use git command line tool to do a little bit hard work:

https://github.com/randomwangran/computing/commit/1d881f7be956f05d980c56644a793239eb599685
