### ISSUE TITLE
关于会刊授权问题

### ISSUE THREAD

**Issue by yangxcasdu** [casdu/huikan#8]
目前已做工作

1. 撰写邀请函。
2. 已委托主编对文编进行任务分配，三天之内询问作者意见。
3. 等待会刊作者回信。

CASDU山大车协十五季会刊电子版化邀请函

亲爱的十五季车协会刊的各位作者:
我是十五季会刊文编之一，目前协会正在进行往年会刊电子版转载工作，也就是将去年我们已经发布的纸质版会刊以纯文字稿的形式整理到Github的casdu账号上（目前由11级WR协助），并实时更新，目前第十四季会刊（2018年度）已经由前辈更新转载完毕，其他年度会刊也在获取授权和整理中。
感谢你为会刊贡献出最宝贵的文字，每一本会刊都凝聚着这一届车协人的感悟，传递着我们的感动和温暖。我们的想法很简单，让会刊的文字被更多的车协人或者同样喜欢骑车的人看到，即在作者授权同意下将十五季会刊电子版上传至Github，在此征求你的同意。
如果你愿意的话，请告知正在联系你的会刊文编们，如果觉得不太合适，也请告诉我们你的想法和困惑，我们会尊重每一个作者的建议。
【山大车协，永不止步！】

附：
【关于会刊电子版转载的通知】
http://bbs.casdu.cn/forum.php?mod=viewthread&tid=11669&fromuid=36346
(出处: 山东大学自行车协会论坛)

CASDU十五季会刊小组/ YX
2020年2月16日

**Comment by randomwangran** [comment]
Just a tiny modification. @yangxcasdu 

> 目前由11级xx管理
> 目前由11级xx协助

**Comment by randomwangran** [comment]
Just for security issue.

**Comment by yangxcasdu** [comment]
ok

**Comment by yangxcasdu** [comment]
是否可以尝试  在即将转载的这期会刊中询问作者敏感信息的加密问题？

什么信息是最重要的，什么信息是次重要的？

初略查看目前已有的文字稿，例如 分部门工作总结中不可避免提及人名，如果进行修改，需要修改地方太多。但是随感一类的文章，需要修改地方比较少，只需要对作者进行名字改动（拼音、网名、省略姓氏）。

一是 文编与作者之间联系-反馈之间增加的额外工作量，最好在我们商量好一种比较好的方案后，再进行工作。

二是对于转载后其他读者是否能够通顺阅读，不造成障碍，这可能是作者自己需要考虑的。

**Comment by randomwangran** [comment]
> 是否可以尝试 在即将转载的这期会刊中询问作者敏感信息的加密问题？

Yes. it is important. What is your timeline to send the mail to the author?

**Comment by randomwangran** [comment]
> 什么信息是最重要的，什么信息是次重要的？

I need to think about it and disucuss with you.

**Comment by randomwangran** [comment]
> 初略查看目前已有的文字稿，例如 分部门工作总结中不可避免提及人名，如果进行修改，需要修改地方太多。但是随感一类的文章，需要修改地方比较少，只需要对作者进行名字改动（拼音、网名、省略姓氏）。

as long as we know the name, it is really easy to replace all of them using some programming language. It's easy.

**Comment by randomwangran** [comment]
~~example is like:~~

~~my real name: Ran Alice~~

~~On this digital huikan~~

~~We just use name:~~

~~Alice.~~

**Comment by randomwangran** [comment]
> 一是 文编与作者之间联系-反馈之间增加的额外工作量，最好在我们商量好一种比较好的方案后，再进行工作。

Agree with you, we need discussion before reach out.

**Comment by randomwangran** [comment]
> 二是对于转载后其他读者是否能够通顺阅读，不造成障碍，这可能是作者自己需要考虑的。

yes. that's an issue, but we can discuss how to solve it.

**Comment by randomwangran** [comment]
If you need quick feed back, or already send them out please let me know.

I change my time schedual to handle this.

**Comment by randomwangran** [comment]
How about this:

https://github.com/casdu/security-issue/issues/5#issuecomment-586799836

We just replace their real name to their initials?

In this case, we do not need extra work. And achieve the security goal?

For all those replacement work, leave it to our programmer.

**Comment by randomwangran** [comment]
There's no 100% security method, just a relative thing.

But, we can do something.

**Comment by randomwangran** [comment]
Don't get me wrong. You made decision. I try to help if you want.

**Comment by randomwangran** [comment]
> 二是对于转载后其他读者是否能够通顺阅读，不造成障碍，这可能是作者自己需要考虑的。


or we can keep the real name version private, but not put them online?

I think we need the real name version. It makes us feel good.

We can walk around this surely.

If we need to communicate priviately, we can discuss here:

https://github.com/casdu/security-issue/issues/6

**Comment by yangxcasdu** [comment]
抱歉，今天开始上课，所以刚才看到回复。

昨天晚上我对我所负责约稿的十位同学进行了询问，他们其中只有一位没有回复，其余都回复可以。
所以初步的反馈来说，对于电子版化转载的是基本同意的。

但是我觉得可能自己没有把涉及敏感信息这个问题告诉他们，或者他们本身对GITHUB平台不熟悉。

目前我准备联系其余的文编，如果没有进行第一次询问，暂停正在进行的工作。
等待我们讨论方案出来之后再开始？

刚收到主编的反馈，约50位作者大概有10位还没有回复，其余均为同意。

**Comment by yangxcasdu** [comment]
我赞同保留真实姓名的版本，可以采用纸质会刊的电子版pdf版本放在论坛的形式保存，目前19年度会刊已经这样做了。但是目前我们所做的工作在Github平台上加密是必要的。

我个人对加密任务的任务量想得过于复杂，人名改动可以由在github上的我们自己完成，不必要再文编和作者反复确认，但是可以告知作者 我们采取了这样的方式以及用意，我相信他们会理解。

至于加密方法，采用拼音是否可行，全拼最易于理解。
 张三用Zhangsan ＞zhangz≈zhsan。

所以接下来，在告知作者之后。我决定对我正在编辑的19会刊中每一篇文章中的作者姓名以及文中提及的全称姓名进行pingyin处理（若提及外号或者非全称则仍然用原文）。

最后，在完成量约一半左右，邀请协会同学进行一次阅读体验的问卷调查。

若可行，接下来的工作就比较明朗了。

**Comment by randomwangran** [comment]
> 抱歉，今天开始上课，所以刚才看到回复。

没事的，这不是负担。

> 但是我觉得可能自己没有把涉及敏感信息这个问题告诉他们，或者他们本身对GITHUB平台不熟悉。

是这样的，很多时候是大家没有意识到而已。

> 张三用Zhangsan ＞zhangz≈zhsan。

可行，我稍后写一个脚本，向你展示。

> 等待我们讨论方案出来之后再开始？

没有问题的，安全方面的考虑，做出过高假设是非常必要的。

> 我决定对我正在编辑的19会刊中每一篇文章中的作者姓名以及文中提及的全称姓名进行pingyin处理

[好的，我来写脚本。](https://github.com/casdu/security-issue/blob/master/chinese-name-to-ini/replace.el)

> 若可行，接下来的工作就比较明朗了。

不用担心，技术上是可行的。

**Comment by yangxcasdu** [comment]
今天我会将 “加密姓名‘操作和用意 通过主编的联系 告知各位作者。

是否已经可以这么做了？

**Comment by randomwangran** [comment]
> 是否已经可以这么做了？

Please don't ask me the decision.

You made decision, I try to help.

If you ask questions, I would like to anwser.

> 是否已经可以这么做了？

My opinion: I think it's okay.

Don't put any expection on me. I can only provide very limmited help.

**Comment by yangxcasdu** [comment]
我的意思是 方案是否已经讨论成熟的意思。

按照目前的讨论来说，这应该是比较好的  ：）

**Comment by randomwangran** [comment]
> 我的意思是 方案是否已经讨论成熟的意思。

I don't know what is 成熟.

> 按照目前的讨论来说，这应该是比较好的 ：）

If you think it's okay, then do it.

I also think so.

**Comment by randomwangran** [comment]
If you have any issue, just reopen.
